name: TranscriptomeAtlas
channels:
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::python=3.5

  # Package managers
  - conda-forge::uv

  # Development environment
  - conda-forge::jupyter

  # Documentation
  - conda-forge::quarto

  # Bioinformatics tools
